import { MetalFamily, MetalOrderStatus } from "@prisma/client";

export const METAL_FAMILY_LABELS: Record<MetalFamily, string> = {
  MAT_OFICINA: "Material de Oficina",
  LIMPIEZA:    "Limpieza",
  ALMACEN_TQ:  "Almacén TQ",
};

export const METAL_FAMILY_OPTIONS = (Object.keys(METAL_FAMILY_LABELS) as MetalFamily[]).map(
  (key) => ({ value: key, label: METAL_FAMILY_LABELS[key] })
);

export const MATERIAL_CATALOG: Record<MetalFamily, string[]> = {
  MAT_OFICINA: [
    "Bolígrafo adhesivo de peana negros",
    "Bolígrafo rojo bic",
    "Bolígrafo negro bic",
    "Bolígrafo azul bic",
    "Lápiz",
    "Goma",
    "Afilador",
    "Permanente punta fina negro M",
    "Permanente punta fina rojo M",
    "Permanente punta gruesa negro M",
    "Subrayador amarillo",
    "Subrayador rosado",
    "Subrayador naranja",
    "Subrayador azul",
    "Cinta adhesiva mediana (12 mm. x 66 m)",
    "Cinta adhesiva grande gruesa",
    "Porta cinta adhesiva grande negra",
    "Fundas finas de Cartapacio",
    "Clips",
    "Regla",
    "Tijeras negras",
    "Tipex",
    "Imperdibles grandes",
    "Elásticos",
    "Grapas 22/6",
    "Grapadora 22/6",
    "Paquete de folios",
    "Archivadores rojos",
    "Carpeta plástica azules",
    "Calculadora negra",
    "Libreta azules",
    "Rollo datáfono",
    "Pincho de tickets",
    "Pegamento de barra mediano",
    "Poscit TQ",
    "Caja sobres marrones 500 unidades",
    "Pegatinas sobres medida 24",
    "Pilas botón mandos (especificar referencia)",
    "Pilas normales AA",
    "Pilas cuadradas para caja fuerte 9V",
    "Pilas pequeñas para mando AAA",
    "Cinta velcro 25m",
    "Alfombrilla para ratón negra",
    "Bolsas autocierre (indicar medida)",
    "Bolsas blancas plásticas",
    "Alicates punta fina",
    "Alicates punta gruesa",
    "Bolsas envío RC Y VR",
    "Etiquetas blancas para joyas",
    "Protector de monedas (especificar tamaño)",
    "Cajonera de pendientes",
  ],
  LIMPIEZA: [
    "Guantes Nitrilo TALLA S NEGRO",
    "Guantes Nitrilo TALLA M NEGRO",
    "Guantes Nitrilo TALLA L NEGRO",
    "Guantes Nitrilo Talla XL NEGRO",
    "Abrillantador de plata ALADDIN",
    "Algodón",
    "Papel Higiénico",
    "Bolsas de basuras pequeñas 30L",
    "Estropajo",
    "Paño para mostrador",
    "Paño para limpiar cristales",
    "Escobillón (sin palo)",
    "Recogedor (Pala de escobillón)",
    "Cubo de Fregona",
    "Fregona sin palo",
    "Palo de Fregona",
    "Agua destilada (para pesas de agua)",
    "Limpiador multiusos / Limpiacristales",
    "Jabón FAIRY (Limpiar prendas)",
    "Jabón de manos para baño 5L",
    "Jabón de manos desinfectante (Con Alcohol) 5L",
    "Saniter M",
    "Fregasuelos 5L",
    "Anti cucarachas",
    "Anti moscas",
    "Servilletas Duras",
    "Servilletas Blandas",
    "Ambientador",
    "Alcohol 5L",
    "Multibac (líquido para desinfección de zonas)",
    "Cartel suelo mojado",
    "Mopa para parquet",
    "Palo para mopa parquet",
    "Soporte metal para mopa",
    "Líquido limpia parquet",
    "Acetona para taller (solo Isaac)",
  ],
  ALMACEN_TQ: [
    "Cajas de Packaging pequeñas",
    "Cajas de Packaging mediana",
    "Cajas de Packaging Grandes",
    "Cajas de Packaging Pulsera",
    "Cajas de Packaging Reloj",
    "Bolsas Packaging (Guapa, Guapao)",
    "Bolsas Zip regalo Pequeña",
    "Bolsas Zip regalo Mediana",
    "Expositor goma Boca-Nariz",
    "Expositor oreja goma",
    "Expositor gargantillas pequeño",
    "Expositor pendientes blancos 6 uni",
    "Expositor metracrilato transparente pendientes",
    "Expositor metracrilato Argollas",
    "Expositor metracrilato pulsera",
    "Expositor pendientes piramidal",
    "Libreta caja",
    "Libreta Trabajos",
    "Tarjetas tiendas adhesivas",
    "Tarjetas diamantes José Miguel",
    "Rollo papel impresora ticket",
    "Pistola de códigos (mal estado / defectuoso)",
    "Teclado numérico inalámbrico",
    "Teclado inalámbrico con ratón (mal estado / defectuoso)",
    "Toner Brother (poner número de toner)",
    "Gamuza Limpia joyas",
    "Ácido Rosado (Limpiar prendas)",
    "Caja para Ácidos",
    "Ácido Oro 9/10k",
    "Ácido Oro 14K",
    "Ácido Oro 18K",
    "Ácido AG (plata)",
    "Pinzas para los Ácidos",
    "Piedra de toque",
    "Lima",
    "Lupa",
    "Imán",
    "Martillo de fibra",
    "Pesa",
    "Lija para piedra de toque",
    "Medidor de anillos / Lastra",
    "Anillero",
    "Cepillo de pelos (Limpiar prendas)",
    "Cepillo de pelos metal (Limpiar prendas)",
    "Regla de diamantes",
    "Guantes para máquina de pulir",
    "Tester Diamantes (mal estado / defectuoso)",
    "Pasta de pulir",
    "Piedra Verde (solo para corian)",
  ],
};

export const METAL_ORDER_STATUS_LABELS: Record<MetalOrderStatus, string> = {
  BORRADOR:   "Borrador",
  ENVIADO:    "Enviado",
  CONFIRMADO: "Confirmado",
  PREPARANDO: "Preparando",
  EN_CAMINO:  "En camino",
  ENTREGADO:  "Entregado",
  CANCELADO:  "Cancelado",
};

export const METAL_ORDER_STATUS_COLORS: Record<MetalOrderStatus, string> = {
  BORRADOR:   "bg-slate-100 text-slate-600",
  ENVIADO:    "bg-yellow-100 text-yellow-700",
  CONFIRMADO: "bg-blue-100 text-blue-700",
  PREPARANDO: "bg-indigo-100 text-indigo-700",
  EN_CAMINO:  "bg-purple-100 text-purple-700",
  ENTREGADO:  "bg-green-100 text-green-700",
  CANCELADO:  "bg-red-100 text-red-600",
};
